name: "ci environment setup"
description: |
  * set up color diagnostics for clang
  * set home bazelrc

inputs:
  buildbuddy_api_key:
    required: false

runs:
  using: "composite"
  steps:
    - name: install libtinfo5
      shell: bash
      # clang tools load libtinfo5 for color diagnostics but `ubuntu-latest`
      # runners already have `libtinfo.so.6` installed. We just create a
      # symlink since it's faster than installing libtinfo5.
      # https://github.com/circleci/circleci-images/issues/430#issuecomment-522602495
      run: |
        sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

    - name: setup ci bazelrc
      shell: bash
      run: |
        cp .github/workflows/ci.bazelrc ~/.bazelrc
        echo 'build --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy_api_key }}' >> ~/.bazelrc

