name: "ci environment setup"
description: |
  * set up color diagnostics for clang
  * set home bazelrc

inputs:
  bazel-cache-key:
    required: false
    default : bazel-external-cache
  buildbuddy-api-key:
    required: false

runs:
  using: "composite"
  steps:
    - name: install libtinfo5
      shell: bash
      # clang tools load libtinfo5 for color diagnostics but `ubuntu-latest`
      # runners already have `libtinfo.so.6` installed. We just create a
      # symlink since it's faster than installing libtinfo5.
      # https://github.com/circleci/circleci-images/issues/430#issuecomment-522602495
      run: |
        sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

    - name: setup ci bazelrc
      shell: bash
      run: |
        cp .github/workflows/ci.bazelrc ~/.bazelrc
        echo 'build --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy-api-key }}' >> ~/.bazelrc

    - name: setup bazel install base, output base, repository cache
      shell: bash
      run: |
        echo "startup --install_base=$HOME/bazel_cache/install_base" >> ~/.bazelrc
        echo "startup --output_base=$HOME/bazel_cache/output_base" >> ~/.bazelrc
        echo "common --repository_cache=$HOME/bazel_cache/repository_cache" >> ~/.bazelrc

    - name: restore bazel install base, output base, repository cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/bazel_cache/install_base
          ~/bazel_cache/output_base/external
          ~/bazel_cache/repository_cache
        key: ${{ inputs.bazel-cache-key }}
