#pragma once

#include "geometry/src/algebra.hpp"
#include "geometry/src/algebra_type.hpp"
#include "geometry/src/common_algebra_type.hpp"
#include "geometry/src/dual.hpp"
#include "geometry/src/exterior_product.hpp"
#include "geometry/src/geometric_product.hpp"
#include "geometry/src/get.hpp"
#include "geometry/src/interior_product.hpp"
#include "geometry/src/multivector_for.hpp"
#include "geometry/src/regressive_product.hpp"
#include "geometry/src/sum.hpp"
#include "geometry/src/to_multivector.hpp"
#include "geometry/src/type_list.hpp"
