name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gcc, clang]
        feature: ['', asan, tsan, ubsan]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel \
          test \
          --config=${{ matrix.toolchain }} \
          --features=${{ matrix.feature }} \
          //...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run //tools:lcov_list

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./bazel-out/_coverage/_coverage_report.dat
        fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flag:
          - '--config=clang-format'
          - '--config=clang-tidy'
          - '--config=verbose-clang-tidy'
          - '--compilation_mode=opt'
        exclude:
          - flag: ${{ github.event_name == 'pull_request' && '--config=verbose-clang-tidy' || 'dummy' }}

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel build ${{ matrix.flag }} //...

  buildifier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-env-setup
      with:
        buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
    - run: |
        bazel run //tools:buildifier.check
